eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
logging:
  level:
    io:
      seata: debug
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: io.seata.sample.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8184
spring:
  application:
    name: order-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?serverTimezone=Asia/Shanghai
    username: root
    password:
